apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-updater-binding
  namespace: develop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-updater
subjects:
  - kind: ServiceAccount
    name: jenkins-updater
    namespace: jenkins
