apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mariadb
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      volumes:
        - name: mariadb-data
          persistentVolumeClaim: { claimName: mariadb-data }
      containers:
        - image: docker.io/library/mariadb
          name: mariadb
          volumeMounts:
            - mountPath: /var/lib/mysql
              name:      mariadb-data
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: mot-de-passe-root
          startupProbe: &probe
            exec:
              command:
                - "sh"
                - "-c"
                - "mariadb-admin status -p$MARIADB_ROOT_PASSWORD"
          livenessProbe: *probe
          readinessProbe: *probe
