apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    grafana_datasource: "1"
  name: prometheus-operator-elasticsearch-datasource
  namespace: monitoring
data:
  elasticsearch.yaml: |-
    apiVersion: 1
    datasources:
      - name: Elasticsearch
        type: elasticsearch
        access: proxy
        database: "[filebeat-*-]YYYY.MM.DD-*"
        url: http://elasticsearch-master.elasticsearch:9200
        jsonData:
          interval: Daily
          timeField: "@timestamp"
          esVersion: "7.10.0"
