apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mailpit.fullname" . }}
  labels:
    {{- include "mailpit.labels" . | nindent 4 }}
data:
  MP_QUIET: "true"
  MP_DATABASE: "/maildir/mailpit.db"
