# All available values:
# https://github.com/kubernetes-sigs/external-dns/blob/master/charts/external-dns/values.yaml

provider: google # or azure or aws (default = aws)

# Google cloudDNS credentials
google:
  project: "eni-kubernetes"
  serviceAccountSecret: "cloud-dns-key"

sources:
  - service
  - ingress
  - istio-gateway
  - gateway-httproute

# TXT prefix
txtPrefix: "k8s-"
