# https://github.com/istio/istio/blob/master/manifests/charts/gateway/values.yaml

autoscaling:
  minReplicas: 2

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - istio-ingress
        topologyKey: kubernetes.io/hostname

