global:

  k8sIngress:
    enabled: true
    enableHttps: true
    gatewayName: ingressgateway

  sds:
    enabled: true
    udsPath: "unix:/var/run/sds/uds_path"
    useNormalJwt: true

nodeagent:
  enabled: true
  env:
    CA_PROVIDER: "Citadel"
    CA_ADDR: "istio-citadel:8060"
    VALID_TOKEN: true

gateways:
  istio-ingressgateway:
    sds:
      enabled: true

mixer:
  policy:
    enabled: true

  telemetry:
    enabled: true
    resources:
      requests:
        cpu: 50m
        memory: 100Mi

pilot:
  traceSampling: 100.0
