ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
  hosts:
    - name: "wordpress-istio.eni.yannig.ovh"
  tls:
    - hosts:
        - "wordpress-istio.eni.yannig.ovh"
      secretName: wordpress-istio-eni-yannig-ovh-tls
