apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: mailhog
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mailhog
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
