controller:
  customInitContainers:
    - name: set-pvc
      image: "alpine:3"
      imagePullPolicy: IfNotPresent
      command: ["chown", "-R", "1000:1000", "/var/jenkins_home"]
      securityContext:
        runAsUser: 0
        runAsNonRoot: false
      volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
  ingress:
    enabled: true
    ingressClassName: nginx
    hostName: jenkins.eni.yannig.ovh
    annotations:
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    tls:
      - secretName: jenkins.eni.yannig.ovh
        hosts:
          - "jenkins.eni.yannig.ovh"
