apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mailpit
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 10Mi
  volumeName: pv-mailpit
