apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailpit
  namespace: test-istio
spec:
  selector:
    matchLabels:
      app: mailpit
      version: v1
  template:
    metadata:
      labels:
        app: mailpit
        version: v1
    spec:
      containers:
      - image: axllent/mailpit
        name: mailpit
        ports:
          - containerPort: 1025
          - containerPort: 8025
