apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabelAppKubernetesIoName
metadata:
  name: k8s-required-label-app-kubernetes-io-name
spec:
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
    namespaces: ["test"]
  enforcementAction: "deny"