apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: anonymous-viewer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: viewer
subjects:
- kind: User
  name: system:anonymous
