apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "pod-and-container-limit"
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "2"
        memory: "300M"
    - type: "Container"
      max:
        cpu: "1"
        memory: "240M"
      default:
        cpu: "300m"
        memory: "200Mi"
      defaultRequest:
        cpu: "200m"
        memory: "100Mi"
      maxLimitRequestRatio:
        cpu: "4"
        memory: "2"
