# https://github.com/bitnami/charts/blob/master/bitnami/wordpress/values.yaml

ingress:
  ingressClassName: nginx
  enabled: true
  tls: true
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hostname: "wordpress.eni.yannig.ovh"

mariadb:
  networkPolicy: &disable
    enabled: false
networkPolicy: *disable
readinessProbe: *disable
