apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eni-yannig-ovh
spec:
  secretName: eni-yannig-ovh-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "eni.yannig.ovh"
  dnsNames: ["eni.yannig.ovh", "*.eni.yannig.ovh"]
