apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mon.adresse@email.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress: {}
          # Set class to use a specific http entrypoint
          # class: nginx
      - dns01:
          cloudDNS:
            # A secretKeyRef to a google cloud json service account
            serviceAccountSecretRef:
              name: cloud-dns-key
              key: credentials.json
            # The project in which to update the DNS zone
            project: "eni-kubernetes"
        selector:
          dnsZones:
            - eni.yannig.ovh
