apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mailpit
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mailpit
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: AverageValue
          averageUtilization: 50
