resources:
  limits:
    cpu: "1"
    memory: "2048Mi"
  requests:
    cpu: "200m"
    memory: "1536Mi"

extraInitContainers:
  - name: file-permissions
    image: busybox:latest
    command: ['chown', '-R', '1000:1000', '/usr/share/elasticsearch/']
    volumeMounts:
    - mountPath: /usr/share/elasticsearch/data
      name: elasticsearch-master
    securityContext:
      runAsUser: 0
