# Disable dashboard
dashboard_enabled: no

# Retrieve cluster kubeconfig
kubeconfig_localhost: yes

# Activate Ingress controller
ingress_nginx_enabled: yes

# Activate Helm Tiller
helm_enabled: true
