k8s-cluster:
  vars:
    ansible_become: yes
    ansible_user: "root"

  children:
    kube-node:
      hosts:
        worker1: {}
        worker2: {}

    kube-master:
      hosts:
        master: {}

    etcd:
      hosts:
        master: {}

bastion:
  hosts:
    rebond:
      ansible_become: no
      ansible_user: "roger"
      masters: "master"
      workers: "worker1 worker2"
