apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eni-yannig-ovh
  namespace: istio-system
spec:
  secretName: eni.yannig.ovh
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "eni.yannig.ovh"
  dnsNames:
    - "eni.yannig.ovh"
    - "*.eni.yannig.ovh"
