apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mailpit.fullname" . }}
  labels:
    {{- include "mailpit.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}