apiVersion: v1
kind: Service
metadata:
  name: {{ include "mailpit.fullname" . }}
  labels:
    {{- include "mailpit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      appProtocol: http
      name: http
    - port: {{ .Values.service.smtp.port }}
      targetPort: smtp
      protocol: TCP
      appProtocol: smtp
      name: smtp
  selector:
    {{- include "mailpit.selectorLabels" . | nindent 4 }}
