apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mailhog
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: hdd
  resources:
    requests:
      storage: 10Mi
  volumeName: pv-mailhog
