apiVersion: batch/v1
kind: CronJob
metadata:
  name: kube-hunter
spec:
  schedule: "0 12 * * *"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
          - name: kube-hunter
            image: aquasec/kube-hunter 
            command: ["kube-hunter"]
            args:
              - "--pod"
              - "--token"
              - "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0aW1lIjoxNjQwOTUwNzE3LjgyMDExODQsImVtYWlsIjoieWFubmlnLnBlcnJlQGxhcG9zdGUubmV0IiwiciI6IjlmOWQzNzI3In0.XUlw9V_LpI_uIe_MEX2UP7isxkf-LI4edj9YxIKpPuE"
          restartPolicy: Never
      backoffLimit: 4
